# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ./builtin-audio.nix
      ./disable-i2c-wakeup.nix
      ./displays.nix
      ./fix-ish-firmware.nix
      ./key-remap.nix
      ./power.nix
      # ./usbguard.nix
    ];

  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "xe" "usbhid" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices.cryptlvm =
    { device = "/dev/disk/by-uuid/30811f95-f536-4131-ab09-bd1adc605f81";
      allowDiscards = true;
      bypassWorkqueues = true;
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d38efa68-1200-4912-86f7-2ec133450e34";
      fsType = "btrfs";
      options = [ "subvol=nixos" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d38efa68-1200-4912-86f7-2ec133450e34";
      fsType = "btrfs";
      options = [ "subvol=nixos/home" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BE97-EF72";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/tmp" =
    { device = "none";
      fsType = "tmpfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics.enable32Bit = true;
  hardware.sensor.iio.enable = true;

  hardware.graphics.extraPackages = with pkgs; [
    intel-media-driver
    intel-compute-runtime
    vpl-gpu-rt
  ];
  hardware.graphics.extraPackages32 = with pkgs.driversi686Linux; [
    intel-media-driver
  ];

}
