# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  #boot.kernelPackages = pkgs.linuxPackages_5_6;
  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"
    "hid_microsoft" "intel_wmi_thunderbolt" "r8152" "thunderbolt" "i915" "hid_generic" "xhci_hcd" "usbhid"
    ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
  #  "systemd.restore_state=0"
  #  "button.lid_init_state=method"
  #  "snd_hda_intel.dmic_detect=0"
  #  "snd-intel-dspcfg.dsp_driver=1"
  ];

  boot.initrd.luks.devices."nixos" =
    { device = "/dev/disk/by-uuid/ba1da5c5-c0f5-4ea1-ad74-5e168ddf41e9";
      allowDiscards = true;
    };

  #boot.extraModprobeConfig = ''
  #  options cfg80211 cfg80211_disable_40mhz_24ghz=1
  #'';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a6fd74c-293b-4190-a458-458421d1a910";
      fsType = "btrfs";
      options = [ "subvol=nixos" "noatime" "autodefrag" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2ECE-55C6";
      fsType = "vfat";
    };


  fileSystems."/tmp" =
    { device = "none";
      fsType = "tmpfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 100;
  nix.buildCores = lib.mkDefault 8;

  hardware.opengl.driSupport32Bit = true;

  hardware.cpu.intel.updateMicrocode = true;

  hardware.sensor.iio.enable = true;

  # hardware.firmware = with pkgs; [ alsa-sof-firmware ];

  services.pipewire.enable = true;
  services.pipewire.pulse.enable = true;
  security.rtkit.enable = true;

  hardware.pulseaudio.enable = false;
  hardware.pulseaudio.extraModules = with pkgs; [ pulseaudio-modules-bt ];

  services.power-profiles-daemon.enable = false;
  services.tlp.enable = true;
  services.tlp.settings = {
    CPU_SCALING_GOVERNOR_ON_AC = "powersave";
    CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    CPU_ENERGY_PERF_POLICY_ON_AC = "balance_performance";
    CPU_ENERGY_PERF_POLICY_ON_BAT = "balance_power";
    CPU_HWP_ON_AC = "balance_performance";
    CPU_HWP_ON_BAT = "balance_power";
    ENERGY_PERF_POLICY_ON_AC = "balance_performance";
    ENERGY_PERF_POLICY_ON_BAT = "balance_power";
    SCHED_POWERSAVE_ON_AC = 1;
    SCHED_POWERSAVE_ON_BAT = 1;

    DISK_DEVICES = "nvme0n1";

    USB_AUTOSUSPEND = 0;
    USB_BLACKLIST = "0bda:8153";

    DISK_APM_LEVEL_ON_BAT = "254";

    DEVICES_TO_DISABLE_ON_LAN_CONNECT = "wifi";
    DEVICES_TO_ENABLE_ON_LAN_DISCONNECT = "wifi";
  };

  services.undervolt = {
    enable = true;
    coreOffset = -80;
  };

  services.thermald = {
    enable = true;
    configFile = ./thermal-conf.xml.default;
  };

}
